chore(범승): 23-11-02 web에 JWT 다시 넣기
in-ch/tech-inverview-study pull request #32
Opened 2023-11-02 10:23 UTC by bumsly

2023-11-03 13:10 UTC, in-ch requested changes
확인 요망

2023-11-03 13:10 UTC, in-ch commented on web/README.md
> +1. 세션 저장소와 같은 별도의 인증 저장소가 ‘필수’가 아니다. -> 서버의 상태를 저장하지 않으므로 서버는 클라이언트의 상태를 추적하거나 세션을 유지할 필요가 없다. (2)
(2)은 머임? 오타인가

2023-11-05 02:45 UTC, bumsly commented on web/README.md
> +1. 세션 저장소와 같은 별도의 인증 저장소가 ‘필수’가 아니다. -> 서버의 상태를 저장하지 않으므로 서버는 클라이언트의 상태를 추적하거나 세션을 유지할 필요가 없다. (2)
오타 맞지

2023-11-05 09:40 UTC, in-ch commented on web/README.md
> +1. 세션 저장소와 같은 별도의 인증 저장소가 ‘필수’가 아니다. -> 서버의 상태를 저장하지 않으므로 서버는 클라이언트의 상태를 추적하거나 세션을 유지할 필요가 없다. (2)
오타와 관련해서 Issue 생성함 
수정 ㄱㄱㄱ
[이슈 보기](https://github.com/in-ch/tech-inverview-study/issues/33)

2023-11-06 14:03 UTC, closed without merging